### ISSUE TITLE
Create setup procedure

### ISSUE THREAD

**Issue by travisormsby** [Ziiiiing/netlogo-GIS8501#1]
The setup procedure should spawn some number of white and black turtles.  Will probably need to use the "breed" method to create two different types so different attributes can be assigned to each.

**Comment by millsm278** [comment]
#First attempt at setup procedure
--------------------------------------------

breed [Bs B]
breed [Ws W]

to setup
  clear-all
  create-Bs 10 [ setxy random-xcor random-ycor ]
  ask Bs [ set color green ]
  create-Ws 100 [ setxy random-xcor random-ycor ]
  ask Ws [ set color white ]
  reset-ticks
end

**Comment by travisormsby** [comment]
That seems good to me, at least to get us started.  Do we want to do this like the official GitHub way, and you create it in a feature branch, then make a pull request to have it merged into master?

**Comment by millsm278** [comment]
#attempt 2 - using system dynamics model (see sheep v wolves model)

breed [Bs B]
breed [Ws W]

;; System dynamics model globals
globals [
  ;; constants
  Bs-birth-rate
  Ws-birth-rate
  ;; size of each step, see SYSTEM-DYNAMICS-GO
  dt
]

;; Initializes the system dynamics model.
;; Call this in your model's SETUP procedure.
to system-dynamics-setup
  reset-ticks
  set dt 0.001
  ;; initialize constant values
  set Bs-birth-rate .45
  set Ws-birth-rate 0.26
  ;; initialize stock values

end

;; Call this in your model's GO procedure.
to system-dynamics-go


  tick-advance dt
end


to setup
  clear-all
  system-dynamics-setup
  create-Bs 3 [ setxy random-xcor random-ycor ]
  ask Bs [ set color green ]
  create-Ws 300 [ setxy random-xcor random-ycor ]
  ask Ws [ set color white ]

end

to go
  system-dynamics-go
end

**Comment by millsm278** [comment]
Hey Travis, I just saw your last comment. yes, I think that sounds good. I will create a branch & pull req

**Comment by travisormsby** [comment]
Maggie, can this issue be closed?
