### ISSUE TITLE
Create turtle movement procedure

### ISSUE THREAD

**Issue by travisormsby** [Ziiiiing/netlogo-GIS8501#2]
Turtles should move randomly until they come to a suitable patch (no covenant restricting their type, not already occupied).  Then they should stop.

**Comment by Ziiiiing** [comment]
breed[Bs B]
breed[Ws W]

; define two variables belonging to each turtle
turtles-own [
  home?                ; for each turtle, indicates whether turtles find a proper place to settle down
  other-nearby-2       ; how many two-patch away turtles with different color
]

to setup
  clear-all
  create-Bs 10 [setxy random-xcor random-ycor]
  ask Bs [set color green]
  create-Ws 100 [setxy random-xcor random-ycor]
  ask Ws [set color white]
  reset-ticks
end

; run the model
; all initial turtles are homeless
to go
  if all? turtles [home?] [stop]
  move-homeless-turtles
  update-turtles
end

; homeless turtles try a new spot
to move-homeless-turtles
  ask turtles with [not home?]
  [find-new-spot]
end

; move until the homeless turtles find an unoccupied patch
to find-new-spot
  rt random-float 360                           ; give them random headings
  if any? other turtles-here [find-new-spot]    ; make sure the new places thet found are unoccupied patches
  move-to patch-here                            ; move to center of unoccupied patch
end

to update-turtles
  ask turtles [
    set other-nearby-2 count (turtles in-radius 2) with [color != [color] of myself]
    set home? turtles-here = 0 and other-nearby-2 = 0
  ]
end

**Comment by travisormsby** [comment]
Can you incorporate this code into the CovanentSpread.nlogo file, test it to make sure it works correctly, and submit a pull request?

**Comment by Ziiiiing** [comment]
I tried yesterday but it seems not working.
I will try again later. Thanks for your advice. See you later.

Gene

**Comment by Ziiiiing** [comment]
Hey Travis, I think I have figured out the question you mentioned in the
latest comment.

**Comment by travisormsby** [comment]
Gene, can this issue be closed?

**Comment by Ziiiiing** [comment]
For sure!  Thanks Travis.
