### ISSUE TITLE
export the raster from NetLogo, rasterize Mapping prejudice data

### ISSUE THREAD

**Issue by Ziiiiing** [Ziiiiing/netlogo-GIS8501#32]

**Comment by Ziiiiing** [comment]
Can I close this issue now, Travis?

**Comment by travisormsby** [comment]
Not yet b/c I still need to create a raster of the mapping prejudice data to compare the model output raster to

**Comment by Ziiiiing** [comment]
Okay! Got it.

**Comment by travisormsby** [comment]
closed by #37
